#!/usr/bin/env python3
# =============================================================================
# File        : omnic.py
# Description : Omni-C High-Level Protocol Compiler CLI Frontend (omnibus-cc)
# License     : MIT License
# =============================================================================

import sys
import os
import argparse
import subprocess

# Ensure sdk and python directories are in sys.path
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
SDK_DIR = os.path.join(PROJECT_ROOT, "sdk")

if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)
if SDK_DIR not in sys.path:
    sys.path.insert(0, SDK_DIR)

from omnibus.compiler.driver import OmniCCompiler
import python.omnibus_asm as asm_tool


def main():
    parser = argparse.ArgumentParser(
        description="Omni-C (omnibus-cc) High-Level Protocol Compiler",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python omnic.py uart_echo.c -o uart_echo.asm
  python omnic.py spi_flash.c -o spi_flash.asm --hex spi_flash.hex
  python omnic.py dht11.c -o dht11.asm --mem dht11.mem --verify
        """
    )

    parser.add_argument("source", help="Source Omni-C file (.c)")
    parser.add_argument("-o", "--output", help="Output assembly file (.asm)")
    parser.add_argument("-I", "--include", action="append", default=[], help="Additional include directory")
    parser.add_argument("--hex", help="Output Intel/Verilog hex format file (.hex)")
    parser.add_argument("--bin", help="Output raw binary instruction file (.bin)")
    parser.add_argument("--mem", help="Output Verilog $readmemh format file (.mem)")
    parser.add_argument("--header", help="Output C header file with binary array (.h)")
    parser.add_argument("--no-opt", action="store_true", help="Disable peephole optimizer & sidecar delay packing")
    parser.add_argument("--verify", action="store_true", help="Verify generated assembly with omnibus_asm.py")

    args = parser.parse_args()

    if not os.path.isfile(args.source):
        print(f"[!] Error: Source file '{args.source}' not found.")
        sys.exit(1)

    print(f"[*] Compiling Omni-C source '{args.source}'...")

    compiler = OmniCCompiler(include_paths=args.include, optimize=not args.no_opt)
    try:
        asm_code = compiler.compile_file(args.source)
    except Exception as e:
        print(f"[!] Compilation failed: {e}")
        sys.exit(1)

    # Determine assembly output file
    output_asm = args.output
    if not output_asm:
        base_name = os.path.splitext(args.source)[0]
        output_asm = base_name + ".asm"

    with open(output_asm, "w", encoding="utf-8") as f:
        f.write(asm_code)
    print(f"[+] Emitted OmniBus Assembly: '{output_asm}' ({len(asm_code.splitlines())} lines)")

    # Run assembler if binary/hex/mem requested or --verify
    if args.hex or args.bin or args.mem or args.header or args.verify:
        print(f"[*] Assembling microcode via omnibus_asm.py...")
        assembler = asm_tool.OmnibusAssembler()
        try:
            words, labels = assembler.assemble(asm_code)
            print(f"[+] Assembled {len(words)} instructions successfully:")
            for addr, word, line in words:
                print(f"  [{addr:02d} | 0x{addr:02X}]: 0x{word:04X}  --  {line}")

            if args.hex:
                with open(args.hex, "w", encoding="utf-8") as hf:
                    for addr, word, _ in words:
                        hf.write(f"@{addr:02X} {word:04X}\n")
                print(f"[+] Wrote Intel/Verilog hex format: '{args.hex}'")

            if args.mem:
                with open(args.mem, "w", encoding="utf-8") as mf:
                    for addr, word, _ in words:
                        mf.write(f"{word:04X}\n")
                print(f"[+] Wrote Verilog $readmemh format: '{args.mem}'")

            if args.bin:
                import struct
                with open(args.bin, "wb") as bf:
                    for addr, word, _ in words:
                        bf.write(struct.pack("<H", word))
                print(f"[+] Wrote binary image: '{args.bin}'")

            if args.header:
                with open(args.header, "w", encoding="utf-8") as cf:
                    cf.write("// Auto-generated by Omni-C (omnibus-cc)\n")
                    cf.write(f"const uint16_t microcode[{len(words)}] = {{\n")
                    for addr, word, line in words:
                        cf.write(f"    0x{word:04X}, // [{addr:02d}] {line}\n")
                    cf.write("};\n")
                print(f"[+] Wrote C header image: '{args.header}'")

        except Exception as e:
            print(f"[!] Assembler error: {e}")
            sys.exit(1)


    print("[+] Omni-C compilation complete.")


if __name__ == "__main__":
    main()
