// Auto-generated by Omni-C (omnibus-cc)
const uint16_t microcode[12] = {
    0xF19C, // [00] AUDIO_VOL 0x0C
    0xF1ED, // [01] AUDIO_PLAY 29, 205
    0x01A8, // [02] NOP [0x61A8]
    0xF1E7, // [03] AUDIO_PLAY 23, 183
    0x01A8, // [04] NOP [0x61A8]
    0xF1E3, // [05] AUDIO_PLAY 19, 247
    0x01A8, // [06] NOP [0x61A8]
    0xF1EE, // [07] AUDIO_PLAY 14, 230
    0x0150, // [08] NOP [0xC350]
    0xF1F0, // [09] AUDIO_STOP
    0x01A8, // [10] NOP [0x61A8]
    0x8001, // [11] JMP lbl_while_start_1
};
